import Head from "next/head";
import Layout from "@/components/Layout";
import PostCard from "@/components/PostCard";
import { useEffect, useState } from "react";
import { AppDispatch, RootState } from "@/store";
import Cookies from "js-cookie";
import { login } from "@/store/slices/authSlice";
import { useRouter } from "next/navigation";
import LoginPage from "./auth/login";
import CreatePost from "@/components/CreatePost";
import { useSelector } from "react-redux";
import { getAllPosts } from "@/store/slices/postCardSlice";

export default function Home() {
  const [loginControl, setLoginControl] = useState<boolean>(false);
  const { userPost, posts, liked } = useSelector(
    (state: RootState) => state.post
  );

  const { authData, OtherUser } = useSelector((state: RootState) => state.auth);

  const dispatch = AppDispatch();
  const refreshCookie = Cookies.get("login");
  const router = useRouter();

  useEffect(() => {
    if (refreshCookie) {
      dispatch(login(JSON.parse(refreshCookie)));
      setLoginControl(true);
    } else {
      setLoginControl(false);
      router.push("/auth/login");
    }
  }, [login]);

  useEffect(() => {
    dispatch(getAllPosts());
  }, [liked, userPost]);

  return (
    <>
      <Head>
        <title>Social Media App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-7xl mx-auto">
        {loginControl ? (
          <Layout>
            <CreatePost />
            {posts?.map((item: any) => {
              return (
                <PostCard
                  description={item?.description}
                  image={item?.image}
                  id={item?.user?._id}
                  title={item?.user?.userName}
                  profileImage={item?.user?.profilePicture}
                  liked={item?.liked}
                  key={item?._id}
                  postId={item?._id}
                />
              );
            })}
          </Layout>
        ) : (
          <LoginPage />
        )}
      </main>
    </>
  );
}

// export async function getServerSideProps() {
//   const res = await postCardService.getAllPost();
//   return {
//     props: {
//       data: res.data,
//     },
//   };
// }
